"""Pin the pure-Python arm7 FK against the verified reference.

Reference: ARM7_KINEMATIC_SPEC.md section 5 — nine anchor poses generated by
the C++ implementation (and cross-checked against the p5.js POC's FK to
machine precision). The Python FK must agree to well under 1 µm.
"""
import math

import numpy as np
import pytest

from service import arm7

# (name, q, expected tool0 position [m], expected tool0 z-axis direction or None)
ANCHORS = [
    ("zero",           [0.0] * 7,                            (0.0, 0.0, 1.266), (0.0, 0.0, 1.0)),
    ("yaw",            [math.pi / 2] + [0.0] * 6,            (0.0, 0.0, 1.266), None),
    ("shoulder fwd",   [0.0, math.pi / 2] + [0.0] * 5,       (0.926, 0.0, 0.340), (1.0, 0.0, 0.0)),
    ("shoulder back",  [0.0, -math.pi / 2] + [0.0] * 5,      (-0.926, 0.0, 0.340), (-1.0, 0.0, 0.0)),
    ("shoulder roll",  [0.0, 0.0, math.pi / 2] + [0.0] * 4,  (0.0, 0.0, 1.266), None),
    ("elbow fwd",      [0.0, 0.0, 0.0, math.pi / 2] + [0.0] * 3, (0.526, 0.0, 0.740), (1.0, 0.0, 0.0)),
    ("forearm roll",   [0.0, 0.0, 0.0, 0.0, math.pi / 2] + [0.0] * 2, (0.0, 0.0, 1.266), None),
    ("wrist fwd",      [0.0, 0.0, 0.0, 0.0, 0.0, math.pi / 2, 0.0], (0.126, 0.0, 1.140), (1.0, 0.0, 0.0)),
    ("tool roll",      [0.0] * 6 + [math.pi / 2],           (0.0, 0.0, 1.266), None),
]

TOL = 1e-9  # m — far tighter than any mm-precision readout


@pytest.mark.parametrize("name, q, pos, z_dir", ANCHORS, ids=[a[0] for a in ANCHORS])
def test_anchor_positions(name, q, pos, z_dir):
    tool0 = arm7.tool0_pose(q)
    np.testing.assert_allclose(tool0[:3, 3], pos, atol=TOL)
    if z_dir is not None:
        # the tool z-axis (3rd column of the rotation) must point the expected way
        np.testing.assert_allclose(tool0[:3, 2], z_dir, atol=TOL)


def test_zero_pose_is_straight_up():
    tool0 = arm7.tool0_pose([0.0] * 7)
    np.testing.assert_allclose(tool0[:3, 3], (0.0, 0.0, 1.266), atol=TOL)
    np.testing.assert_allclose(tool0[:3, :3], np.eye(3), atol=1e-12)


def test_position_invariant_joints_rotate_the_frame():
    # J1/J3/J5/J7 do not move the tool position but must rotate the frame:
    # all four are rolls/yaws about the (vertical) arm spine, so a +90 deg
    # excursion must rotate tool0 by +90 deg about world z.
    rz = np.array([[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]])
    for joint in (0, 2, 4, 6):
        q = [0.0] * 7
        q[joint] = math.pi / 2
        tool0 = arm7.tool0_pose(q)
        np.testing.assert_allclose(tool0[:3, 3], (0.0, 0.0, 1.266), atol=TOL)
        np.testing.assert_allclose(tool0[:3, :3], rz, atol=1e-9)


def test_link_frame_contract():
    frames = arm7.link_frames([0.1] * 7)
    assert len(frames) == 8
    for f in frames:
        assert f.shape == (4, 4)
    # pivot heights at zero pose: J2/J3 at 0.340, J4/J5 at 0.740, J6/J7 at 1.140
    zero = arm7.link_frames([0.0] * 7)
    np.testing.assert_allclose(zero[1][:3, 3], (0, 0, 0.340), atol=1e-12)
    np.testing.assert_allclose(zero[3][:3, 3], (0, 0, 0.740), atol=1e-12)
    np.testing.assert_allclose(zero[5][:3, 3], (0, 0, 1.140), atol=1e-12)


def test_fk_callback_rejects_bad_input():
    with pytest.raises(ValueError):
        arm7.fk_callback([0.0] * 6)
